In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [55]:
df_personagens = pd.read_csv('dataset_personagens.csv')
df_personagens

             personagem  quantidade_falas
0      TYRION LANNISTER              1644
1              JON SNOW              1046
2      CERSEI LANNISTER               917
3    DAENERYS TARGARYEN               916
4       JAIME LANNISTER               909
..                  ...               ...
477     RIVERLANDS LORD                 1
478      DORNISH PRINCE                 1
479       IRONBORN LORD                 1
480           VALE LORD                 1
481   UNSULLIED CAPTAIN                 1

[482 rows x 2 columns]

In [56]:
df_dicionario = pd.read_csv('personagens_dicionario.csv')
df_dicionario

,Nome,Variações,Familia
0,Tyrion Lannister,"TYRION, TRION, TYRIOM, YTRION",Lannister
1,Jon Snow,"JON, JOHN",Stark/Night's Watch
2,Cersei Lannister,"CERSEI, CESEI, CERSIE, ERSEI",Lannister
3,Daenerys Targaryen,"DAENERYS, DANY, DANAERYS, DENERYS, DAEYNERYS, ...",Targaryen
4,Jaime Lannister,JAIME,Lannister
...,...,...,...
154,Wun Wun,WUN WUN,Gigante
155,Lyanna Mormont,LYANNA MORMONT,Mormont
156,Septa Mordane,"SEPTA MORDANE, MORDANE",Fé dos Sete
157,Biter,BITER,Criminoso
158,Rhaegar Targaryen,"RHAEGAR TARGARYEN, RHAEGAR",Targaryen

In [57]:
df_interacoes = pd.read_csv('dataset_interacoes_personagens.csv')
df_interacoes

C:\Users\carlo\AppData\Local\Temp\ipykernel_18940\2635396455.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_interacoes = pd.read_csv('dataset_interacoes_personagens.csv')

,temporada,episodio,cena,descricao_cena,falante_oficial,ouvinte_oficial,fala,tamanho_fala,num_personagens_cena,tipo_interacao
0,1,1,0,[First scene opens with three Rangers riding t...,WAYMAR ROYCE,WILL,What d’you expect? They’re savages. One lot st...,136,4,group
1,1,1,0,[First scene opens with three Rangers riding t...,WAYMAR ROYCE,GARED,What d’you expect? They’re savages. One lot st...,136,4,group
2,1,1,0,[First scene opens with three Rangers riding t...,WAYMAR ROYCE,YOHN ROYCE,What d’you expect? They’re savages. One lot st...,136,4,group
3,1,1,0,[First scene opens with three Rangers riding t...,WILL,GARED,I’ve never seen wildlings do a thing like this...,103,4,group
4,1,1,0,[First scene opens with three Rangers riding t...,WILL,WAYMAR ROYCE,I’ve never seen wildlings do a thing like this...,103,4,group
...,...,...,...,...,...,...,...,...,...,...
585385,8,6,0,NaN,ALL,RIVERLANDS LORD,The Queen in the North! The Queen in the North...,119,22,group
585386,8,6,0,NaN,ALL,YOHN ROYCE,The Queen in the North! The Queen in the North...,119,22,group
585387,8,6,0,NaN,ALL,DAENERYS TARGARYEN,The Queen in the North! The Queen in the North...,119,22,group
585388,8,6,0,NaN,ALL,SANSA STARK,The Queen in the North! The Queen in the North...,119,22,group
585389,8,6,0,NaN,ALL,EDMURE TULLY,The Queen in the North! The Queen in the North...,119,22,group

In [58]:
df_interacoes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 585390 entries, 0 to 585389
Data columns (total 10 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   temporada             585390 non-null  int64
 1   episodio              585390 non-null  int64
 2   cena                  585390 non-null  int64
 3   descricao_cena        1699 non-null    object
 4   falante_oficial       585390 non-null  object
 5   ouvinte_oficial       585390 non-null  object
 6   fala                  585369 non-null  object
 7   tamanho_fala          585390 non-null  int64
 8   num_personagens_cena  585390 non-null  int64
 9   tipo_interacao        585390 non-null  object
dtypes: int64(5), object(5)
memory usage: 44.7+ MB

In [59]:
print(f'Total de interações: {len(df_interacoes):,}')
print(f'Personagens únicos (falantes): {df_interacoes.falante_oficial.nunique()}')
print(f'Personagens únicos (ouvintes): {df_interacoes.ouvinte_oficial.nunique()}')

Total de interações: 585,390
Personagens únicos (falantes): 381
Personagens únicos (ouvintes): 381